### ISSUE TITLE
LZ 1.4

### ISSUE THREAD

**Issue by GM21GM** [GM21GM/LB_324#1]
---

## Acceptance Criteria

|     Given      |       When        |          Then          |  
| :------------: | :---------------: | :--------------------: |  
| An order exists | The order status changes | An email notification is sent to the customer |  
| A customer unsubscribes from notifications | The order status changes | No email notification is sent to the customer |  

---

## Subtasks
- [x] Create an email template for order status updates  
- [ ] Integrate order status tracking into the notification system  
- [ ] Add a "unsubscribe from notifications" option for customers  

---

## Further Information
Make sure the email includes the following details:  
- Order number  
- Updated status (e.g., "Shipped," "Delivered")  
- Estimated delivery date (if applicable)
